### PR TITLE
fix(test):

### PR DESCRIPTION
**Pull request by jfrancai**
Fix failed tests:
    - custom matcher toBeForbidden()
    - custom matcher toRevert()
    - custom matcher toBeAllowed()
    - balancer bb-a-USD pool address

### CODE REVIEW

**Comment by jfschwarz** [comment]
Hey @jfrancai 👋  Thank you for contributing and getting the tests up-and-running again. (We should really re-enable running them for PRs.)

Apparently those balancer addresses were accidentally deleted. 😲 

The changes you applied to the custom matchers don't seem to work on my machine. I assume there could be inconsistencies in how the caught errors are structured depending on the RPC node used. Can you share which provider you're using?

**Comment by jfrancai** [comment]
Hello! @jfschwarz 😃 Thanks for the feedback, yes I guess it's related to that, I'm using the one provided in the package.json file (https://rpc.ankr.com/eth).

The weird thing is that I also have inconsistencies on my side, in the sense that when I run tests in isolation like the one for uniswap for example (using jest --runInBand --testPathPattern './src/protocols/uniswap'), they work fine but when run all together with jest --runInBand, it fails. I'm still looking but I'm probably missing something, maybe you have an idea?

**Comment by jfschwarz** [comment]
@jfrancai Not sure, but test issues could be related to throttling of RPC requests from Ankr. Like if there are too many requests due to running a larger number of tests, throttling kicks in and makes the tests fail or run into timeouts.

We've been using some unlimited private endpoints to improve test performance and reliability. 

@nledo Let's try to get the CI job running again using the Karpatey Alchemy node? Then at least we'll all see the same test results and can use them as a reference when running tests locally.

**Comment by jfschwarz** [comment]
> I assume there could be inconsistencies in how the caught errors are structured depending on the RPC node used.

It could also potentially be related to the anvil version, since I don't see any issues with the current version of matchers and the Ankr RPC. Which one are you using, @jfrancai? (`anvil -V`)

**Comment by jfrancai** [comment]
> > I assume there could be inconsistencies in how the caught errors are structured depending on the RPC node used.
> 
> It could also potentially be related to the anvil version, since I don't see any issues with the current version of matchers and the Ankr RPC. Which one are you using, @jfrancai? (`anvil -V`)

I'm using `anvil 0.2.0 (bfc6549 2024-05-07T00:18:05.525782863Z)`

**Comment by jfschwarz** [comment]
fixed in #175

**Pull request closed without merging**
